using ChessPieces.board;
using ChessPieces.pieces;

public class Program
{
    private static void Main(string[] args)
    {
        List<Piece> pieces = new List<Piece>() {
            new Rook(),
            new Knight(),
            new Queen(),
            new King(),
            new Bishop(),
            new Pawn(),
        };

        int count = 0;

        string docPath = Environment.CurrentDirectory
                            .Replace(Path.Combine("bin", "Debug", "net8.0"), "");

        // output the individual count to a text file 
        using StreamWriter file = new StreamWriter(Path.Combine(docPath, "pieces_count.txt"));

        foreach (var piece in pieces)
        {
            string pieceName = piece.GetType().Name;

            file.WriteLineAsync($"Initiating count for piece: {pieceName}.");

            Console.WriteLine($"Initiating count for piece: {pieceName}.");

            // recursive function
            count = Board.GeneratePhoneNumbers(piece);

            Console.WriteLine($"Numbers generated by {pieceName}: {count}");
            file.WriteLineAsync($"Valid numbers generated by {pieceName}: {count}\n");
        }
    }

    
}




